### ISSUE TITLE
Kodi Plugin

### ISSUE THREAD

**Issue by urnenfeld** [ruvelro/TV-Online-TDT-Spain#12]
Hola,
He hecho un sencillo plugin de Kodi el cual se nutre de vuestro readme.md para generar las entradas.
Os interesaria añadirlo al repositorio?

**Comment by ruvelro** [comment]
Estaría genial poder añadirlo :D

**Comment by urnenfeld** [comment]
Perfecto! Algunos detalles antes del pull request:

- Como lo llamamos? (Ahora mismo se llama tdtiberia)
- Los plugins se contienen en una carpeta con el nombre plugin.video.xxxx en nuestro caso plugin.vide.tdtiberia (o el que se decida). En que lugar del repo lo subo?

1. /plugin.vide.tdtiberia
2. /kodi/plugin.vide.tdtiberia
3. /plugins/plugin.vide.tdtiberia
4. /plugins/kodi/plugin.vide.tdtiberia
5. ...

**Comment by ruvelro** [comment]
Buenas.

El nombre tdtiberia está bien. 
En cuanto a la ruta, el segundo está bien, dentro de /kodi/plugin.vide.tdtiberia.

Saludos.

**Comment by urnenfeld** [comment]
Creado pull request #13
