### ISSUE TITLE
Detalles

### ISSUE THREAD

**Issue by edkalrio** [ruvelro/TV-Online-TDT-Spain#14]
Versión 1.0!! Esto va creciendo muy rápido y hay que tomar decisiones para que luego no haya problemas de escalabilidad y portabilidad. He estado revisando el plugin de kodi y me parece incorrecto depender de una tabla markdown. Deberías elaborar una versión agnóstica para su lectura automática. Aunque ahora están muy de moda las APIs en JSON, me parece que por las características del proyecto, una API en CSV sería suficiente para facilitar el parsing. 

También he visto que has firmado la versión con una clave GPG nueva que no coincide con tu clave pública de [keybase](https://keybase.io/ruvelro/pgp_keys.asc?fingerprint=6f2779df25a75852a0039304fe8d8aa9091fb2b6).

No me queda claro la frecuencia de actualización de la lista de canales en kodi. Si es muy habitual, merecería la pena utilizar un CDN para su distribución. Te dejo una TODO list resumen:

- [ ] API
- [x] GPG
- [ ] [RawGit](https://rawgit.com/)

**Comment by urnenfeld** [comment]
Hola,
Comento algunos puntos por alusiones:

1) Estoy de acuerdo que no es lo más elegante. Pero como el autor del proyecto mantiene un md, inicié el trabajo a partir de ese fichero, sin forzar el mantenimiento de varios ficheros. Por otro lado el .md es facil de mantener y colaborar por personas menos expertas. Desde mi punto de vista, es mas critico que las URLs funcionen. 

2) Si te refieres a los commits del 12 de Noviembre, entiendo que es mi mala costumbre de no tener configurado ei repositorio local.

**Comment by edkalrio** [comment]
1. La principal diferencia sería utilizar `,` en vez de `|` como separador :joy:. Podría modificar [tvdownloader](https://github.com/ruvelro/TV-Online-TDT-Spain/blob/1.00/tvdownloader) para generarlo automáticamente.
2. Me refiero a la versión [1.0](https://github.com/ruvelro/TV-Online-TDT-Spain/releases/tag/1.00) que viene firmada con 4AEE18F83AFDEB23 mientras que tu keybase tiene un fingerprint FE8D8AA9091FB2B6.

**Comment by ruvelro** [comment]
Buenas.

Yo creo que está bien tal como está planteado ahora. Al final, la lista de canales del repositorio es la que se irá actualizando, por lo que acceder al MD directamente garantiza al add-on tener siempre los últimos canales, incluso aunque los usuarios no lo actualicen.

Además, como dice urnenfeld, de esta manera es más fácil que otros usuarios puedan añadir nuevos canales, incluso modificar los canales que estén caídos.

Yo creo que para la finalidad del plugin está bien como está ahora, funciona, que es lo más importante.

**Comment by ruvelro** [comment]
La versión 1.0 la he generado y subido yo para facilitar el uso del plugin y no tener que comprimirlo.

**Comment by edkalrio** [comment]
Olvida lo del fingerprint. Resulta que es un comportamiento errático de github. Si lo subes desde la web te lo firma con su clave aunque tengas tú una propia.

Parece que a mí también me lo ha hecho un par de veces. :sweat_smile:

**Comment by urnenfeld** [comment]
@edkalrio Realmente estoy de acuerdo, cuando escribía el codigo parseando el md, me daba cuenta lo fragil que sería ante cualquier modificación. Supongo que la solucion ideal sera un md que se generara automaticamente por un JSON... o cualquier cosa que nos perimitiera solo mantener 1 fichero y mantuviera la comodidad que comenta @ruvelro. Lo del RawGit tambien es muy interesante, tampoco estuve comodo cogiendo la url del md de esa forma.

**Comment by ruvelro** [comment]
Podemos actualizarlo y mejorarlo, aunque yo por falta de tiempo no puedo estar al 100%, y tampoco conozco muy bien el tema de RawGit, seguro que entre los dos tenéis grandes ideas para mejorar y hacer más grande a este proyecto 👍

**Comment by urnenfeld** [comment]
@ruvelro Me gusta el enfoque actual, cuando realmente sea un problema podremos abordarlo con las ideas aqui presentadas. En cuanto al RawGit es más un detalle de implementacion del plugin. De nuevo, si deja de funcionar, pues tenemos plan B :)

**Comment by urnenfeld** [comment]
@edkalrio Puedes comentar un poco que es tvdownloader? De donde viene o quien mantiene ese "ch_channel.php"? Que relacion tiene con el .md de este repositorio?

**Comment by ruvelro** [comment]
@urnenfeld Ese PHP es la fuente de donde saco los canales del MD. Ese fichero lo utiliza una app para ver la TDT de iOS, y mediante sniffing lo pillé para poder crear esta lista abierta.

El TVdownloader es solo un parser que escribió @edkalrio para eliminar paja del PHP y poder ver las direcciones fácilmente, pero hasta el momento el proceso para añadir esas URLs al MD es manual.

**Comment by vk496** [comment]
También creo que sería mejor adaptar el modelo actual a uno más flexible.

Por ejemplo, estaría bien poner logo a cada uno de los canales, información del canal (sacada de su web dinamicame?), etc.

Si es por la presentación en el MK, es posible hacer un parser a la inversa: los cambios en el JSON (por ejemplo), actualizan automáticamente la tabla del MK (vía TravisCI, por ejemplo).

Salu2

**Comment by vk496** [comment]
Dejo aquí una prueba de concepto en la que se puede trabajar con JSON. Además, actualiza diariamente el estado de los canales en la página principal

[https://github.com/vk496/TV-Online-TDT-Spain](https://github.com/vk496/TV-Online-TDT-Spain)


Salu2

**Comment by urnenfeld** [comment]
La intención del campo "enable" del JSON seria la misma que la del Status del .MD ?

PS: :white_check_mark: es mas "Work Friendly" que :green_heart: :)

**Comment by vk496** [comment]
No.

Pensé que ese campo podría ser útil en el futuro (desactivar canales que ya no funcionen sin tener que actualizar el plugin?). No tiene un propósito por ahora.

Salu2

**Comment by urnenfeld** [comment]
@vk496 Estaria bien que efectivamente reflejara cuales parecen no funcionar, como se computa en el script que genera el MD. Así no se añadirian en el proceso de carga del plugin.

Pase lo que pase, voy añadiendo al plugin con esta otra forma de extraer los canales: https://github.com/urnenfeld/TV-Online-TDT-Spain/commit/591e301260276ef51f6e9e1c73741df2a2fbd243

**Comment by ruvelro** [comment]
Está genial la implementación de @vk496, se puede añadir a esta lista para controlar igualmente los canales que funcionan y no funcionan.

**Comment by urnenfeld** [comment]
@ruvelro Si, Opino que en la lista deberían aparecer todos, incluso aunque aun no tengamos una URL... Me referia a reflejar tambien en el JSON el estado de las URL que funcionan o no. Como tenemos un script que lo comprueba estaría bien que se viera también reflejado en el JSON.

Kodi tarda muuucho en darse cuenta que la URL no funciona.... Si hay un proceso offline que lo hace y ya lo deja marcado, pues en kodi podríamos no generar las entradas, o dejarlas al final...

**Comment by vk496** [comment]
Pues cuando tenga un rato, implemento la funcionalidad con ese atributo.

Salu2

**Comment by vk496** [comment]
Buenas, ya he añadido la funcionalidad mencionada en la rama master.

https://github.com/vk496/TV-Online-TDT-Spain

Habría que meter todos los cambios aquí. Ya me diréis cuando y cómo.

Salu2

**Comment by ruvelro** [comment]
¿Cómo podemos meter los cambios en este repositorio desde el tuyo?

**Comment by urnenfeld** [comment]
El pull request no sale automatico, supongo porque el readme.md cambiado demasiado.
Ojo! el JSON no contiene todos los canales actuales del MD, habría que hacer una revision manual que no perdamos nada en la transición.

**Comment by ruvelro** [comment]
Ya he hecho el pull para unir los dos repositorios. Como está pendiente la tarea de actualizar todos los canales, cuando me ponga a ello ya volveré a añadir todos canales que no se hayan sincronizado.

¿Se actualizará la disponibilidad de los canales automáticamente?

**Comment by urnenfeld** [comment]
Quizas falle el deploy.sh? Debería tambien hacer comit del JSON, no veo que se actualice en el repositorio original...

Al menos seguro, habria que cambiar las URLs de los repositorios para que apunte a este y no al de @vk496 .

**Comment by vk496** [comment]
Buenas,

Para que despliegue automáticamente, es necesario configurar TravisCI. Primero, activarlo:

![image](https://user-images.githubusercontent.com/5502443/33245137-dc8fbdde-d303-11e7-911f-078013b61da1.png)

Luego, establecer las variables que le pasaremos al CI:

![image](https://user-images.githubusercontent.com/5502443/33245168-1f4bf4e4-d304-11e7-9fd6-6e9e6e4b6de8.png)

y por último, poner una tarea cron diaria:

![image](https://user-images.githubusercontent.com/5502443/33245174-33f5726c-d304-11e7-8e43-7c6377e46198.png)


PD: Obviamente, en el deploy.sh, habría que cambiar todo lo mio de @vk496 por el username correspondiente.

PD2: Para obtener el token, desde Ajustes, con los siguientes permisos:

![image](https://user-images.githubusercontent.com/5502443/33245196-7c4ad0a2-d304-11e7-80fd-6c75bfec1aeb.png)


PD3: En el branch `develop` de mi repo, he cogido cosas de @urnenfeld . No saco tiempo para hacer más cosas, pero sería interesante coger de ahí en vez del `master`.

Salu2

**Comment by ruvelro** [comment]
En cuanto saque un rato lo hago, que estoy hasta arriba en el trabajo :D 
Gracias.

**Comment by ruvelro** [comment]
Creo que ya debería estar, a ver si cuando se ejecute dentro de dos horas ya funciona esto :D

**Comment by edkalrio** [comment]
Como veo que esto ya está solucionado, voy a ir cerrando este issue para mantener el proyecto ordenado.
