### ISSUE TITLE
Canales Libres

### ISSUE THREAD

**Issue by vk496** [ruvelro/TV-Online-TDT-Spain#16]
Buenas,

He visto por ahí Gol TV. Desconozco si hay más canales de pago, pero sugiero no incluirlos en la lista.

Las razones son obvias: No meterse en tinglados legales si el proyecto crece y, por ende, no ser un plugin pirata más que decae enseguida.

Salu2

**Comment by ruvelro** [comment]
Gol TV creo que es un canal libre, porque emite desde su página web y a través de la TDT, por eso lo añadí. No tiene nada que ver con BeIN o Movistar, los canales de deportes cerrados.

De todas formas, si creeis adecuado eliminarlo, sin problema, y nos aseguramos evitar problemas :D

**Comment by vk496** [comment]
Ups, mil disculpas.

No llegué a comprobarlo. Siempre he creído que era de pago.

Si su web lo emite online, mejor que mejor.
