### ISSUE TITLE
No despliega

### ISSUE THREAD

**Issue by edkalrio** [ruvelro/TV-Online-TDT-Spain#27]
Hace unos días me di cuenta de que Travis no está desplegando el cronjob. Mirando el log, el error aparece en las variables `$GH_USER_EMAIL`, `$GH_USER_NAME` y `$GH_TOKEN` que no han sido inicializadas. Desconozco si se trata un error del [deploy.sh](https://github.com/ruvelro/TV-Online-TDT-Spain/blob/master/.travis/deploy.sh) de @vk496 o de una configuración incompleta de Travis por parte de @ruvelro.

**Comment by vk496** [comment]
Buenas, 

Ya había comentado esto en https://github.com/ruvelro/TV-Online-TDT-Spain/pull/23#issuecomment-348930725

Efectivamente, falta definir esas 3 variables, que deben ser las del autor del repo.

El mío lleva funcionando desde que lo habilité: https://github.com/vk496/TV-Online-TDT-Spain/commits/master

De hecho, sugiero tener una rama de desarrollo, separada del master. Cada día cae un commit automático. Al final se llenará de "basura" y será engorroso buscar cosas o ver trazabilidad.


Salu2
