### ISSUE TITLE
TVE Stream URLs

### ISSUE THREAD

**Issue by jgarrue** [ruvelro/TV-Online-TDT-Spain#32]
Buenas tardes,
Después de unos días peleándome con el tema he conseguido las URL de varios canales de RTVE (aunque La2 se resiste)
A día de hoy funcionan, por si queréis cambiar el readme...
**EDITADO**: 12/01/2018 -> Añadida La2

**TVE1**
http://hlsliveamdgl7-lh.akamaihd.net/i/hlsdvrlive_1@583042/master.m3u8

**TVE2**
http://hlsliveamdgl0-lh.akamaihd.net/i/hlslive_1@586367/master.m3u8

**Canal 24h**
http://hlsliveamdgl8-lh.akamaihd.net/i/hlsdvrlive_1@583030/master.m3u8

**Teledeporte**
http://hlsliveamdgl1-lh.akamaihd.net/i/hlsdvrlive_1@39732/master.m3u8

**Teledeporte HD**
http://hlsliveamdgl1-lh.akamaihd.net/i/hlslive_1@39598/master.m3u8

Por otro lado, las siguientes direcciones también han cambiado:
**Paramount**
http://paramount.live.flumotion.com/live/playlist.m3u8

**Canal Sur Andalucía**
https://www.youtube.com/watch?v=9_mHRWjztNU

**Comment by urnenfeld** [comment]
Tienen buena pinta!
