### ISSUE TITLE
Cuatro HD y Telecinco HD

### ISSUE THREAD

**Issue by saidma** [ruvelro/TV-Online-TDT-Spain#40]
http://cuatro-mediaset-esp-live.secure.footprint.net/mediaset/cuatro/stream2/streamPlaylist.m3u8

http://telecinco-mediaset-esp-live.secure.footprint.net/mediaset/telecinco/stream2/streamPlaylist.m3u8

**Comment by ruvelro** [comment]
Gracias, canales actualizados :D

**Comment by urnenfeld** [comment]
Los anteriores eran validos, (no son HD intencionadamente).
Tendría que crearse otra entrada para HD y dejar los que había.

**Comment by ruvelro** [comment]
Entonces mejor deshacemos y creamos otra entrada.

¿Hay alguna forma de crear una nueva entrada en un número concreto sin tener que cambiar todos los que están ya puestos? Por ejemplo, si quiero meter un canal en concreto en el número 10 sin sumar uno a todos los que van después...

**Comment by urnenfeld** [comment]
@ruvelro el numero id es un identificador, actualmente no se usa. No hay un orden necesario...

Entonces yo utilizaría este campo para identificar el canal no como un orden. Por ejemplo podemos poner los canales de mediaset los primeros 2 digitos "05" y usar otros 2 digitos para el canal. Por ejemplo:

telecinco 0505
cuatro 0504
fdf 0507
....

Sino, como comentas, mover todos los canales es una tarea que realmente no aporta
