### ISSUE TITLE
Crear playlist XSPF para VLC

### ISSUE THREAD

**Issue by EnforcerZhukov** [ruvelro/TV-Online-TDT-Spain#42]
He hecho un script Python que obtiene el JSON de este repositorio y lo convierte a una playlist XSPF, para reproducir directamente en VLC, así no hay que copiar las direcciones de los canales que se quieren ver a mano. Por si os interesa enlazarlo o subirlo al repositorio:

https://github.com/EnforcerZhukov/TDTSpain2VLC

**Comment by ruvelro** [comment]
Muchas gracias por compartirlo, lo enlazamos :D
