### ISSUE TITLE
Betevé no funciona

### ISSUE THREAD

**Issue by Albert456** [ruvelro/TV-Online-TDT-Spain#5]

**Comment by ruvelro** [comment]
Tomo nota. En cuanto encuentre la nueva URL de beteve actualizo la lista de canales. Gracias por avisar.

**Comment by Albert456** [comment]
Tengo este enlace y parece que funciona en varios reproductores.
#EXTINF:-1,Betevé
http://api-cdn.overon.es/SmilLive/getLiveIOS/playlist.m3u8?stream=btv_stream01

**Comment by ruvelro** [comment]
Solucionado. Muchas gracias :D
