### ISSUE TITLE
Ver Antena 3 Portugal

### ISSUE THREAD

**Issue by Quick190** [ruvelro/TV-Online-TDT-Spain#52]
Olá,

Já alguma tempo que não consigo ver a Antena 3. E pelo que parece o link é a funcionar.

Algum motivo para não conseguir ver a Antena 3 desde Portugal?

Obrigado

**Comment by urnenfeld** [comment]
No he probado ultimamente para saber si funciona desde España...
Has probado con el pull request que hay pendiente?

**Comment by Quick190** [comment]
Olá,

Sim, com o pull request pendente já funciona.

Muchas gracias :)
