### ISSUE TITLE
Sugerencia de nuevos canales

### ISSUE THREAD

**Issue by Albert456** [ruvelro/TV-Online-TDT-Spain#6]
#EXTINF:-1,Teledeporte HD
http://rtve-live.hds.adaptive.level3.net/hls-live/rtvegl1-tdphdlv3aomgl1/_definst_/live/stream3.m3u8
#EXTINF:-1,Televisió Badalona
http://cdnlive.shooowit.net/badalonatvlive/smil:live.smil/playlist.m3u8
#EXTINF:-1,Televisió de Girona
http://tvgirona.dnssw.net:1935/live/Icontouch/playlist.m3u8
#EXTINF:-1,Tarragona TV
http://cdns724ste1010.shooowit.net/tac12live/amlst:live/playlist.m3u8
#EXTINF:-1, El Punt Avui TV
http://cdns724ste1010.shooowit.net/puntavuitvlive/smil:live.smil/playlist.m3u8
#EXTINF:-1,Terrassa TV 
http://cast.streamingconnect.tv:1935/terrassaweb/terrassaweb/playlist.m3u8
#EXTINF:-1,Disney Channel
https://eslivestream-lh.akamaihd.net/i/live_1@318671/master.m3u8
#EXTINF:-1,SevillaF.C.
http://sevillafc_live-lh.akamaihd.net/i/video_0@354142/index_0700_av-p.m3u8
#EXTINF:-1,BETISTV
http://rbetis-hls.flumotion.com/rbetis/live/chunklist.m3u8

**Comment by ruvelro** [comment]
Añadidos, gracias.
