### ISSUE TITLE
Error con algunos canales

### ISSUE THREAD

**Issue by LolesLeon** [ruvelro/TV-Online-TDT-Spain#8]
No soy capaz a abrir algunos canales como Neox por ejemplo. Es un error del enlace o de mi configuracion? Donde ver las actualizaciones mas recientes?
Gracias1!

**Comment by LL2** [comment]
A mi me funciona Neox con VLC en Linux(Ubuntu Mate).

**Comment by ruvelro** [comment]
Buenas.

¿Cómo lo intentas abrir? Tienes una guía en la parte superior de la lista de canales, y con esa funcionan la mayoría, entre ellos, Neox.
